baseURL = 'https://blog.tal.bi/'
languageCode = 'en-us'
title = "Ido Talbi's blog"
theme = "anubis"
paginate = 10
enableRobotsTXT = true

# disqusShortname
# googleAnalytics

[author]
name = "Ido Talbi"

[params]
author = "Ido Talbi"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false

# utteranc.es support.
utterancesRepo = "talbii/tal.bi"  # mandatory
utterancesTheme = "github-dark" # optional
utterancesIssue = "url" # optional
utterancesLabel = "blog-comments" # optional

rssAsSocialIcon = true

[[params.social]]
id = "globe"
url = "https://www.tal.bi"

[[params.social]]
id = "github"
name = "talbii"


[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[menu]

[[menu.main]]
identifier = "posts"
name = "All Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
